apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-app.fullname" . }}-secret
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
